In [1]:
import numpy as np
import math as m
import matplotlib.pyplot as plt
import matplotlib.animation as ani
from matplotlib import cm
import sympy as sym
import random as rand
import Data

import Functions_module_beta as fn
from Functions_module_beta import MatrixAction, SystemAction
import custom_functions_01 as cfn
from custom_functions_01 import avg_prob_with_confidence

In [7]:
fn.equations12(fn.TenStateBasis[0],1, False)  # Exampele equation. We'll loop this over the set of 10 basis states to find the 10 equations and then find the matrix.

[cos(2*phi), 0, 0, 0, 0, 0, sqrt(2)*sin(2*phi)/2, -sqrt(2)*sin(2*phi)/2, 0, 0]

In [10]:
Matrix_12 = []
for i in fn.TenStateBasis:
    ith_column = fn.equations12(i,1,False)   # produces effect of sending in ith basis vector
    Matrix_12.append(ith_column)
print('Set of Equations = ',Matrix_12)    # the equations corresponding to M12, the matrix would be transpose

Matrix12 = np.transpose(np.array(Matrix_12))
print('\n Matrix12= \n',Matrix12)   # M12 matrix

Set of Equations =  [[cos(2*phi), 0, 0, 0, 0, 0, sqrt(2)*sin(2*phi)/2, -sqrt(2)*sin(2*phi)/2, 0, 0], [0, cos(phi), 0, -sin(phi), 0, 0, 0, 0, 0, 0], [0, 0, cos(phi), 0, -sin(phi), 0, 0, 0, 0, 0], [0, sin(phi), 0, cos(phi), 0, 0, 0, 0, 0, 0], [0, 0, sin(phi), 0, cos(phi), 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0], [-sqrt(2)*sin(2*phi)/2, 0, 0, 0, 0, 0, cos(phi)**2, sin(phi)**2, 0, 0], [sqrt(2)*sin(2*phi)/2, 0, 0, 0, 0, 0, sin(phi)**2, cos(phi)**2, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]
Matrix12= 
 [[cos(2*phi) 0 0 0 0 0 -sqrt(2)*sin(2*phi)/2 sqrt(2)*sin(2*phi)/2 0 0]
 [0 cos(phi) 0 sin(phi) 0 0 0 0 0 0]
 [0 0 cos(phi) 0 sin(phi) 0 0 0 0 0]
 [0 -sin(phi) 0 cos(phi) 0 0 0 0 0 0]
 [0 0 -sin(phi) 0 cos(phi) 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [sqrt(2)*sin(2*phi)/2 0 0 0 0 0 cos(phi)**2 sin(phi)**2 0 0]
 [-sqrt(2)*sin(2*phi)/2 0 0 0 0 0 sin(phi)**2 cos(phi)**2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


Doing this for the remaining matrices:

In [13]:
Matrix_13 = []
for i in fn.TenStateBasis:
    ith_column = fn.equations13(i,1,False)   # produces effect of sending in ith basis vector
    Matrix_13.append(ith_column)
print('\n \n Set of Equations = ',Matrix_13)    # the equations corresponding to M13, the matrix would be transpose

Matrix13 = np.transpose(np.array(Matrix_13))
print('\n MATRIX13= \n',Matrix13)   # M13 matrix



Matrix_14 = []
for i in fn.TenStateBasis:
    ith_column = fn.equations14(i,1,False)   # produces effect of sending in ith basis vector
    Matrix_14.append(ith_column)
print('\n \n Set of Equations = ',Matrix_14)    # the equations corresponding to M14, the matrix would be transpose

Matrix14 = np.transpose(np.array(Matrix_14))
print('\n MATRIX14= \n',Matrix14)   # M14 matrix


Matrix_23 = []
for i in fn.TenStateBasis:
    ith_column = fn.equations23(i,1,False)   # produces effect of sending in ith basis vector
    Matrix_23.append(ith_column)
print('\n \n Set of Equations = ',Matrix_23)    # the equations corresponding to M23, the matrix would be transpose

Matrix23 = np.transpose(np.array(Matrix_23))
print('\n MATRIX23= \n',Matrix23)   # M23 matrix


Matrix_24 = []
for i in fn.TenStateBasis:
    ith_column = fn.equations24(i,1,False)   # produces effect of sending in ith basis vector
    Matrix_24.append(ith_column)
print('\n \n Set of Equations = ',Matrix_24)    # the equations corresponding to M24, the matrix would be transpose

Matrix24 = np.transpose(np.array(Matrix_24))
print('\n MATRIX24= \n',Matrix24)   # M24 matrix

Matrix_34 = []
for i in fn.TenStateBasis:
    ith_column = fn.equations34(i,1,False)   # produces effect of sending in ith basis vector
    Matrix_34.append(ith_column)
print('\n \n Set of Equations = ',Matrix_34)    # the equations corresponding to M34, the matrix would be transpose

Matrix34 = np.transpose(np.array(Matrix_34))
print('\n MATRIX34= \n',Matrix34)   # M34 matrix


 
 Set of Equations =  [[cos(phi), 0, 0, -sin(phi), 0, 0, 0, 0, 0, 0], [0, cos(2*phi), 0, 0, 0, 0, sqrt(2)*sin(2*phi)/2, 0, -sqrt(2)*sin(2*phi)/2, 0], [0, 0, cos(phi), 0, 0, -sin(phi), 0, 0, 0, 0], [sin(phi), 0, 0, cos(phi), 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0], [0, 0, sin(phi), 0, 0, cos(phi), 0, 0, 0, 0], [0, -sqrt(2)*sin(2*phi)/2, 0, 0, 0, 0, cos(phi)**2, 0, sin(phi)**2, 0], [0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, sqrt(2)*sin(2*phi)/2, 0, 0, 0, 0, sin(phi)**2, 0, cos(phi)**2, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]

 MATRIX13= 
 [[cos(phi) 0 0 sin(phi) 0 0 0 0 0 0]
 [0 cos(2*phi) 0 0 0 0 -sqrt(2)*sin(2*phi)/2 0 sqrt(2)*sin(2*phi)/2 0]
 [0 0 cos(phi) 0 0 sin(phi) 0 0 0 0]
 [-sin(phi) 0 0 cos(phi) 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 -sin(phi) 0 0 cos(phi) 0 0 0 0]
 [0 sqrt(2)*sin(2*phi)/2 0 0 0 0 cos(phi)**2 0 sin(phi)**2 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 -sqrt(2)*sin(2*phi)/2 0 0 0 0 sin(phi)**2 0 cos(phi)**2 0]
 [0 0 0 0 0 0 0 0 0 1]]

 
 Set of Equations =  [[cos(phi), 0, 0

In [23]:
print(Matrix12)
Matrix12.flatten()
# type(Matrix12)
# Matrix12_list = list(np.flatten(Matrix12))
# Matrix12_list

[[cos(2*phi) 0 0 0 0 0 -sqrt(2)*sin(2*phi)/2 sqrt(2)*sin(2*phi)/2 0 0]
 [0 cos(phi) 0 sin(phi) 0 0 0 0 0 0]
 [0 0 cos(phi) 0 sin(phi) 0 0 0 0 0]
 [0 -sin(phi) 0 cos(phi) 0 0 0 0 0 0]
 [0 0 -sin(phi) 0 cos(phi) 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [sqrt(2)*sin(2*phi)/2 0 0 0 0 0 cos(phi)**2 sin(phi)**2 0 0]
 [-sqrt(2)*sin(2*phi)/2 0 0 0 0 0 sin(phi)**2 cos(phi)**2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


array([cos(2*phi), 0, 0, 0, 0, 0, -sqrt(2)*sin(2*phi)/2,
       sqrt(2)*sin(2*phi)/2, 0, 0, 0, cos(phi), 0, sin(phi), 0, 0, 0, 0,
       0, 0, 0, 0, cos(phi), 0, sin(phi), 0, 0, 0, 0, 0, 0, -sin(phi), 0,
       cos(phi), 0, 0, 0, 0, 0, 0, 0, 0, -sin(phi), 0, cos(phi), 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, sqrt(2)*sin(2*phi)/2, 0, 0, 0,
       0, 0, cos(phi)**2, sin(phi)**2, 0, 0, -sqrt(2)*sin(2*phi)/2, 0, 0,
       0, 0, 0, sin(phi)**2, cos(phi)**2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=object)